language: c
compiler:
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; sudo add-apt-repository -y ppa:kubuntu-ppa/backports; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y cmake; fi
  - cmake --version
script: 
  - cmake . 
  - make
notifications:
  email:
    recipients:
      - vorobievds@gmail.com
    on_success: change
    on_failure: always
env:
  - LANG="en_US.UTF-8"
os:
  - linux
